- name: 'Amaru Ahumada'
  pic: 'Amaru_Ahumada.JPG'

- name: 'Gerald Barnert'
  pic: '_Gerald_Barnet.JPG'

- name: 'Christian Briceño'
  pic: 'Christian_Briceño.JPG'

- name: 'Felipe Bustos'
  pic: 'Felipe_Bustos.JPG'

- name: 'Valentina Castro'
  pic: 'Valentina_Castro.JPG'

- name: 'Nicolás Consuegra'
  pic: 'Nicolas_Consuegra.JPG'

- name: 'Esperanza Díaz'
  pic: 'Esperanza_Diaz.JPG'

- name: 'Alonso Díaz'
  pic: 'Alonso_Diaz.JPG'

- name: 'Jorge Gutiérrez'
  pic: 'Jorge_Gutierrez.JPG'

- name: 'Esteban Lopez'
  pic: 'Esteban_Lopez.JPG'

- name: 'Rentato Loyola'
  pic: '_Rentato_Loyola.JPG'

- name: 'Álvaro Manríquez'
  pic: '_Alvaro_Manriquez.JPG'

- name: 'Valentina Nuñez'

- name: 'Monserrat Prado'
  pic: 'Monserrat_Prado.JPG'

- name: 'Camilo Rosas'
  pic: 'Camilo_Rosas.JPG'

- name: 'Cristóbal Tapia'
  pic: 'Cristobal_Tapia.JPG'

- name: 'Cristóbal Torres'
  pic: 'Cristobal_Torres.JPG'

- name: 'Rodrigo Vega'
  pic: 'Rodrigo_Vega.JPG'

- name: 'Tomás Villega'
  pic: 'Tomas_Villega.JPG'

- name: 'Daniel Zaro'
  pic: 'Daniel_Zaro.JPG'
